import java.util.Properties

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
}

/**
 * The local agent travels inside the APK.
 *
 * It is the SAME Node source the PC runs (`pc-agent/src`), staged into assets at
 * build time rather than committed twice:
 *
 *   - it must match this app's protocol version, so a copy shipped separately
 *     (a download, a second artifact) could drift; the app and its agent are one
 *     build.
 *   - it is small: the source plus `ws` (which has no dependencies of its own).
 *
 * `ws` is staged as a plain directory because the sandbox has Node but no npm;
 * a generated package.json marks the tree as an ES module, exactly like
 * pc-agent's own.
 */
val syncLocalAgent by tasks.registering(Copy::class) {
    val pcAgent = rootProject.file("../pc-agent")
    from(pcAgent.resolve("src")) { into("src") }
    from(pcAgent.resolve("node_modules/ws")) { into("node_modules/ws") }
    into(layout.projectDirectory.dir("src/main/assets/local-agent"))
    doLast {
        val marker = layout.projectDirectory.file("src/main/assets/local-agent/package.json").asFile
        marker.writeText(
            """
            {
              "name": "termdesk-local-agent",
              "private": true,
              "type": "module",
              "comment": "generated by the syncLocalAgent task - do not edit"
            }
            """.trimIndent() + "\n",
        )
    }
}

tasks.named("preBuild") { dependsOn(syncLocalAgent) }

android {
    namespace = "dev.termdesk.app"
    compileSdk = 35

    defaultConfig {
        applicationId = "dev.termdesk.app"
        minSdk = 26
        // targetSdk 28, on purpose and with a cost: Android 10+ forbids an app
        // process (untrusted_app) from EXECUTING a file in its own data dir, so
        // a Termux userland unpacked into files/ cannot run at all - measured
        // here: "error=13, Permission denied" on files/usr/bin/bash. Apps that
        // target 28 or lower land in a domain where exec is allowed, which is
        // exactly why Termux itself ships with targetSdkVersion 28.
        //
        // What it costs: legacy (non-scoped) storage behaviour, no Play Store
        // upload without raising it again, and no API-30+ package visibility
        // rules. TermDesk is sideloaded, uses only its own app-specific dirs,
        // and its whole point is running the payload - so the trade is taken
        // knowingly. Set TERMDESK_MODERN_TARGET_SDK=1 to build at 35 instead,
        // which gives up the local kernel and keeps everything else.
        targetSdk = if (System.getenv("TERMDESK_MODERN_TARGET_SDK") == "1") 35 else 28
        versionCode = 4
        versionName = "0.31.0"
    }

    /**
     * Release signing, with the key kept outside the repository.
     *
     * `~/.termdesk/keystore/termdesk-release.properties` names the keystore and
     * its passwords; nothing secret is committed. Without that file a release
     * build would come out unsigned — an APK nobody can install — so the build
     * says so instead of producing one (see documents/打包与试用.md for how the
     * key was made and why losing it matters).
     */
    val signingProps = file(
        System.getProperty("user.home") + "/.termdesk/keystore/termdesk-release.properties",
    )
    signingConfigs {
        if (signingProps.exists()) {
            create("release") {
                val props = Properties().apply {
                    signingProps.inputStream().use { stream -> load(stream) }
                }
                storeFile = file(props.getProperty("storeFile"))
                storePassword = props.getProperty("storePassword")
                keyAlias = props.getProperty("keyAlias")
                keyPassword = props.getProperty("keyPassword")
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            signingConfig = signingConfigs.findByName("release")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
    }
}

dependencies {
    implementation(platform("androidx.compose:compose-bom:2024.12.01"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-extended")
    implementation("androidx.activity:activity-compose:1.9.3")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.7")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7")
    implementation("androidx.core:core-ktx:1.15.0")

    // WebSocket client used to talk to the TermDesk PC agent.
    implementation("com.squareup.okhttp3:okhttp:4.12.0")

    debugImplementation("androidx.compose.ui:ui-tooling")
}
